config/routes.rb
IllinoisFootball::Application.routes.draw do

  get "illinifootball/home", :controller => "illini", :action => "index"
  
  get "illinifootball/home/new", :controller => "illini", :action => "new", :as => :new_illini_team
  post "illinifootball/home/create", :controller => "illini", :action => "create" 
  
  get "illinifootball/home/:id", :controller => "illini", :action => "show", :as => :illini_team
  delete "illinifootball/home/:id", :controller => "illini", :action => "destroy"
  
  get "illinifootball/home/:id/edit", :controller => "illini", :action => "edit", :as => :illini_team_edit
  put "illinifootball/home/:id", :controller => "illini", :action => "update"


end

app/models/football_team.rb
class FootballTeam < ActiveRecord::Base
  attr_accessible :losses, :team, :wins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/illini_controller.rb
class IlliniController < ApplicationController 
  
  def index
    @illini = FootballTeam.all 
  end
  
 def destroy 
    team_id = params['id']
    @illinis = FootballTeam.find_by_id(team_id)
    @illinis.destroy
    redirect_to 'http://localhost:3000/illinifootball/home'
  end
  
  def show 
    team_id = params['id']
    @illinis = FootballTeam.find_by_id(team_id)
  end
  
  def new
  end
  
  def edit 
     team_id = params['id']
    @illinis = FootballTeam.find_by_id(team_id)
  end
  
  def update
     team_id = params['id']
      @illinis = FootballTeam.find_by_id(team_id)
      @illinis.team = params[:team]
      @illinis.wins = params[:wins]
      @illinis.losses = params[:losses]
      @illinis.save
      
      redirect_to "http://localhost:3000/illinifootball/home"
  
  end
  
  
  def create 
    new_team = FootballTeam.new(:team => params['team'], :wins => params['wins'], :losses => params['losses'])
    new_team.save
    
    redirect_to 'http://localhost:3000/illinifootball/home'
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/illini/edit.html.erb
<h1> Edit Your Favorite Illini Team's Info </h1>

	<%= form_tag "http://localhost:3000/illinifootball/home/#{@illinis.id}", :method => :put do %>
			<%= label_tag "Team:" %>
			<%= text_field_tag "team", @illinis.team %>
			<%= label_tag "Wins:" %>
			<%= text_field_tag "wins", @illinis.wins %>
			<%= label_tag "Losses:" %>
			<%= text_field_tag "losses", @illinis.losses %>
			
			<%= submit_tag "Add New Illini Team Info"%>
			
			<%end%>

app/views/illini/index.html.erb
<%# def new_illini_team_url
#	return "http://localhost:3000/illinifootball/home/new"
	
#	end %>

<h1>Greatest Illini Football Teams</h1>



	<%= link_to 'Add your favorite Illini Team', new_illini_team_url %>   
<ul>	
	<%@illini.each do |team|%>
	<li><%= link_to team.team, illini_team_url(team.id)%> 
	 	#of wins <%= team.wins %> : #of losses <%= team.losses%> 
		|
		<%= link_to 'Edit', illini_team_edit_url(team.id)%> 
			|
			
		<%= link_to "Delete", illini_team_edit_url(team.id)
			"http://localhost:3000/illinifootball/home/#{team.id}" , 
			:method => :delete, :confirm => "Are you sure you want to DELETE this GREAT ILLINI TEAM???!!!"%>
		
		</li>
	<%end%>
</ul>		

app/views/illini/new.html.erb
<h1> Add Your Favorite Illini Team <h1>
	
	<%= form_tag "http://localhost:3000/illinifootball/home/create" do %>
		<%= label_tag "Team:" %>
		<%= text_field_tag "team" %>
		<%= label_tag "Wins:" %>
		<%= text_field_tag "wins" %>
		<%= label_tag "Losses:" %>
		<%= text_field_tag "losses" %>
		
		<%= submit_tag "Add A ANOTHER GREAT ILLINI TEAM" %>
		
	<%end %>

app/views/illini/show.html.erb
<h1><%= @illinis.team %> Teams Info </h1>

<li> Team Name: <%= @illinis.team %> </li>
<li> # Wins: <%= @illinis.wins%> </li>
<li> # Losses: <%= @illinis.losses%> </li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IllinoisFootball</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>